---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - amavisd-new
    - clamav-daemon
    - clamav-freshclam
    - dspam
    - fuzzyocr
    - pyzor
    - spamassassin

