---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - clamav-daemon
    - clamav-freshclam
    - clamav-milter

- name: update /etc/clamav/clamav-milter.conf from template
  template:
    src: etc/clamav/clamav-milter.conf
    dest: /etc/clamav/clamav-milter.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart clamav

- name: ensure /var/spool/postfix/clamav directory exists
  file:
    path: /var/spool/postfix/clamav
    owner: clamav
    group: clamav
    mode: 0750
    state: directory

- name: ensure postfix user is a member of clamav group
  user:
    name: postfix
    append: yes
    groups: clamav
    state: present
  notify:
    - restart postfix

- name: ensure clamav services are stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - clamav-daemon
    - clamav-milter

- name: ensure clamav services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - clamav-daemon
    - clamav-milter

