---
- name: ensure dovecot packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - dovecot-antispam
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-managesieved
    - dovecot-pop3d
    - dovecot-sieve

- name: update /etc/dovecote/dovecot.conf from template
  template:
    src: etc/dovecot/dovecot.conf
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dovecot

- name: create maildir in /etc/skel
  command: maildirmake.dovecot {{ mailserver_maildir_name }}
           chdir=/etc/skel
           creates=/etc/skel/{{ mailserver_maildir_name }}

- name: create sent maildir in /etc/skel
  command: maildirmake.dovecot .Sent
           chdir=/etc/skel/{{ mailserver_maildir_name }}
           creates=/etc/skel/{{ mailserver_maildir_name }}/.Sent

- name: create drafts maildir in /etc/skel
  command: maildirmake.dovecot .Drafts
           chdir=/etc/skel/{{ mailserver_maildir_name }}
           creates=/etc/skel/{{ mailserver_maildir_name }}/.Drafts

- name: create trash maildir in /etc/skel
  command: maildirmake.dovecot .Trash
           chdir=/etc/skel/{{ mailserver_maildir_name }}
           creates=/etc/skel/{{ mailserver_maildir_name }}/.Trash

- name: create spam maildir in /etc/skel
  command: maildirmake.dovecot .Spam
           chdir=/etc/skel/{{ mailserver_maildir_name }}
           creates=/etc/skel/{{ mailserver_maildir_name }}/.Spam

- name: ensure /etc/skel/.sieve.d exists and has correct permissions
  file:
    path: /etc/skel/.sieve.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: update /etc/skel/.sieve.d/default from template
  template:
    src: etc/skel/.sieve.d/default.sieve
    dest: /etc/skel/.sieve.d/default.sieve
    owner: root
    group: root
    mode: 0644

- name: ensure /etc/skel/.dovecot.sieve exists and links to .sieve.d/default.sieve
  file:
    path: /etc/skel/.dovecot.sieve
    src: .sieve.d/default.sieve
    force: yes
    state: link

- name: ensure all dovecot services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - dovecot

