---
- name: ensure dovecot packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - dovecot-antispam
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-managesieved
    - dovecot-metadata-plugin
    - dovecot-pop3d
    - dovecot-sieve
    - dovecot-solr
    - solr-tomcat6

- name: update /etc/dovecote/dovecot.conf from template
  template:
    src: etc/dovecot/dovecot.conf
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dovecot

- name: ensure /etc/skel/.sieve.d exists and has correct permissions
  file:
    path: /etc/skel/.sieve.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: update /etc/skel/.sieve.d/default from template
  template:
    src: etc/skel/.sieve.d/default.sieve
    dest: /etc/skel/.sieve.d/default.sieve
    owner: root
    group: root
    mode: 0644

- name: ensure /etc/skel/.dovecot.sieve exists and links to .sieve.d/default.sieve
  file:
    path: /etc/skel/.dovecot.sieve
    src: .sieve.d/default.sieve
    state: link

- name: update /etc/tomcat6/server.xml from template
  template:
    src: etc/tomcat6/server.xml
    dest: /etc/tomcat6/server.xml
    owner: root
    group: root
    mode: 0644
  notify:
    - restart tomcat6

- name: update /etc/solr/conf/solrconfig.xml from template
  template:
    src: etc/solr/conf/solrconfig.xml
    dest: /etc/solr/conf/solrconfig.xml
    owner: root
    group: root
    mode: 0644

- name: update /etc/solr/conf/schema.xml from template
  template:
    src: etc/solr/conf/schema.xml
    dest: /etc/solr/conf/schema.xml
    owner: root
    group: root
    mode: 0644

- name: ensure all dovecot services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - dovecot
    - tomcat6
