---
- name: ensure dspam packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - dspam
    - libdspam7-drv-mysql
    - python-milter
    - python-pip

- name: ensure dspam database is present
  mysql_db:
    name: dspam

- name: ensure dspam database user is present
  mysql_user:
    name: dspam
    host: "{{ item }}"
    password: "{{ mailserver_dspam_mysql_password }}"
    priv: dspam.*:ALL
  with_items:
    - "%"
    - localhost

- name: update /etc/default/dspam from template
  template:
    src: etc/default/dspam
    dest: /etc/default/dspam
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dspam

- name: copy .my.cnf file with dspam password credentials
  template:
    src: var/spool/dspam/.my.cnf
    dest: /var/spool/dspam/.my.cnf
    owner: dspam
    group: dspam
    mode: 0600

- name: create dspam mysql objects tables
  shell: mysql --user=dspam --password="{{ mailserver_dspam_mysql_password }}" dspam < /usr/share/doc/libdspam7-drv-mysql/sql/mysql_objects-4.1.sql && touch /etc/dspam/.mysql_objects
         creates=/etc/dspam/.mysql_objects

- name: create dspam mysql virtual users tables
  shell: mysql --user=dspam --password="{{ mailserver_dspam_mysql_password }}" dspam < /usr/share/doc/libdspam7-drv-mysql/sql/virtual_users.sql && touch /etc/dspam/.mysql_virtual_users
         creates=/etc/dspam/.mysql_virtual_users

- name: update /etc/dspam/dspam.conf from template
  template:
    src: etc/dspam/dspam.conf
    dest: /etc/dspam/dspam.conf
    owner: dspam
    group: dspam
    mode: 0660
  notify:
    - restart dspam

- name: update /etc/dspam/default.prefs from template
  template:
    src: etc/dspam/default.prefs
    dest: /etc/dspam/default.prefs
    owner: dspam
    group: dspam
    mode: 0644
  notify:
    - restart dspam

- name: ensure dspam-milter group exists
  group:
    name: dspam-milter
    state: present

- name: ensure dspam-milter user exists and is in dspam group
  user:
    name: dspam-milter
    group: dspam-milter
    groups: dspam
    append: yes
    home: /
    shell: /bin/false
    state: present

- name: install dspam milter package using pip (not included in Ubuntu)
  pip:
    name: dspam-milter
    state: present

- name: update /etc/init/dspam-milter.conf from template
  template:
    src: etc/init/dspam-milter.conf
    dest: /etc/init/dspam-milter.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dspam

- name: update /etc/dspam/dspam-milter.conf from template
  template:
    src: etc/dspam/dspam-milter.conf
    dest: /etc/dspam/dspam-milter.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dspam

- name: ensure dspam services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - dspam
    - dspam-milter

