---
- name: ensure dspam packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - dspam
    - libdspam7-drv-mysql
    - python-milter
    - python-pip

- name: ensure dspam database is present
  mysql_db:
    name: dspam

- name: ensure dspam database user is present
  mysql_user:
    name: dspam
    host: "{{ item }}"
    password: "{{ mailserver_dspam_mysql_password }}"
    priv: dspam.*:ALL
  with_items:
    - "%"
    - localhost

- name: update /var/spool/dspam/.my.cnf from template
  template:
    src: var/spool/dspam/.my.cnf
    dest: /var/spool/dspam/.my.cnf
    owner: dspam
    group: dspam
    mode: 0600

- name: create dspam mysql objects tables
  shell: >
          perl -pe 's/MyISAM/InnoDB/;' 
          /usr/share/doc/libdspam7-drv-mysql/sql/mysql_objects-4.1.sql |
          mysql -u dspam -p"{{ mailserver_dspam_mysql_password }}" dspam 
          && touch /etc/dspam/.mysql_objects
          creates=/etc/dspam/.mysql_objects

- name: create dspam mysql virtual users tables
  shell: >
          perl -pe 's/MyISAM/InnoDB/;' 
          /usr/share/doc/libdspam7-drv-mysql/sql/virtual_users.sql |
          mysql -u dspam -p"{{ mailserver_dspam_mysql_password }}" dspam
          && touch /etc/dspam/.mysql_virtual_users
          creates=/etc/dspam/.mysql_virtual_users

- name: ensure START=yes in /etc/default/dspam
  lineinfile:
    dest: /etc/default/dspam
    regexp: ^START=
    line: START=yes
    state: present

- name: update /etc/dspam/dspam.conf from template
  template:
    src: etc/dspam/dspam.conf
    dest: /etc/dspam/dspam.conf
    owner: dspam
    group: dspam
    mode: 0640
  notify:
    - restart dspam

- name: update /etc/dspam/default.prefs from template
  template:
    src: etc/dspam/default.prefs
    dest: /etc/dspam/default.prefs
    owner: dspam
    group: dspam
    mode: 0644
  notify:
    - restart dspam

- name: install dspam milter package using pip (not included in Ubuntu)
  pip:
    name: dspam-milter
    state: present

- name: update /etc/init/dspam-milter.conf from template
  template:
    src: etc/init/dspam-milter.conf
    dest: /etc/init/dspam-milter.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dspam

- name: update /etc/dspam/dspam-milter.conf from template
  template:
    src: etc/dspam/dspam-milter.conf
    dest: /etc/dspam/dspam-milter.conf
    owner: postfix
    group: postfix
    mode: 0600
  notify:
    - restart dspam

- name: ensure /var/spool/postfix/dspam exists and has correct permissions
  file:
    path: /var/spool/postfix/dspam
    owner: postfix
    group: postfix
    mode: 0700
    state: directory

- name: ensure dspam services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - dspam
    - dspam-milter

