---
- name: ensure postfix packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - mailutils
    - postfix
    - postfix-pcre
    - postfix-policyd-spf-python

- name: update /etc/mailname from template
  template:
    src: etc/mailname
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: update /etc/postfix/main.cf from template
  template:
    src: etc/postfix/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: update /etc/postfix/master.cf from template
  template:
    src: etc/postfix/master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: update /etc/aliases from template
  template:
    src: etc/aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  register: update_aliases

- name: rehash aliases
  command: newaliases
  when: update_aliases|changed
  notify:
    - restart postfix

- name: ensure all postfix services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - postfix

