---
# FIXME: where does cron-deja-vu go?
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - cron-deja-vu
    - postfix
    - postfix-pcre
    - postfix-policyd-spf-python

- name: update mailname from template
  template:
    src: etc/mailname
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: update main.cf from template
  template:
    src: etc/postfix/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: update master.cf from template
  template:
    src: etc/postfix/master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: update aliases from template
  template:
    src: etc/aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: rehash aliases
  command: newaliases
  notify:
    - restart postfix

- name: ensure all mail services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - postfix

