---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - amavisd-new
    - clamav-daemon
    - clamav-freshclam
    - cron-deja-vu
    - dovecot-antispam
    - dovecot-core
    - dovecot-imapd
    - dovecot-managesieved
    - dovecot-metadata-plugin
    - dovecot-pop3d
    - dovecot-sieve
    - dovecot-solr
    - dspam
    - fuzzyocr
    - opendkim
    - opendkim-tools
    - postfix
    - postfix-gld 
    - postfix-pcre
    - postfix-policyd-spf-python
    - pyzor
    - spamassassin

#- name: ensure gitlabhq_production database is present
#  mysql_db: 
#    name: gitlabhq_production

#- name: ensure git database user is present
#  mysql_user: 
#    name: git
#    host: "{{ item }}" 
#    password: "{{ gitlab_git_mysql_password }}" 
#    priv: gitlabhq_production.*:ALL
#  with_items:
#    - "%"
#    - localhost

- name: update mailname from template
  template:
    src: etc/mailname
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix
    - restart amavis

- name: update default/opendkim from template
  template:
    src: etc/default/opendkim
    dest: /etc/default/opendkim
    owner: root
    group: root
    mode: 0644
  notify:
    - restart opendkim

- name: update opendkim.conf from template
  template:
    src: etc/opendkim.conf
    dest: /etc/opendkim.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart opendkim

- name: create domain key if it does not already exist
  command: opendkim-genkey -t -S -s mail -D /etc/mail -d {{ postfix_domain }}
           creates=/etc/mail/mail.private

- name: update main.cf from template
  template:
    src: etc/postfix/main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: update master.cf from template
  template:
    src: etc/postfix/master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: update aliases from template
  template:
    src: etc/aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: rehash aliases
  command: newaliases
  notify:
    - restart postfix

- name: ensure all mail services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - opendkim
    - postfix

