---
- name: ensure solr tomcat packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - solr-tomcat

- name: update /etc/solr/conf/solrconfig.xml from template
  template:
    src: etc/solr/conf/solrconfig.xml
    dest: /etc/solr/conf/solrconfig.xml
    owner: root
    group: root
    mode: 0644

- name: update /etc/solr/conf/schema.xml from template
  template:
    src: etc/solr/conf/schema.xml
    dest: /etc/solr/conf/schema.xml
    owner: root
    group: root
    mode: 0644

