---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - crm114
    - fuzzyocr
    - libmail-dkim-perl
    - pyzor
    - razor
    - sa-compile
    - spamass-milter
    - spamassassin
    - spamassassin-heatu
    - spamassassin-rules-ja

- name: run pyzor discover...
  command: pyzor discover
  changed_when: false

#- name: run razor-admin register...
#  command: razor-admin -home=/etc/spamassassin/.razor -register
#  changed_when: false

#- name: run razor-admin create...
#  command: razor-admin -home=/etc/spamassassin/.razor -create
#  changed_when: false

#- name: run razor-admin discover...
#  command: razor-admin -home=/etc/spamassassin/.razor -discover
#  changed_when: false

#- name: create spam group for spamd, spamass-milter, and postfix
#  group: 
#    name: spam
#    state: present
  
#- name: create spamd user to run spam assassin daemon
#  user:
#    name: spamd
#    group: spam
#    home: /var/lib/spamassassin
#    shell: /bin/false
#    state: present

#- name: add spamass-milter user to spam group
#  user:
#    name: spamass-milter
#    append: yes
#    groups: spam
#    state: present

#- name: add postfix user to spam group
#  user:
#    name: postfix
#    append: yes
#    groups: spam
#    state: present
#  notify:
#    - restart postfix

- name: update /etc/default/spamassassin from template
  template:
    src: etc/default/spamassassin
    dest: /etc/default/spamassassin
    owner: root
    group: root
    mode: 0644
  notify:
    - restart spamassassin

- name: update init.pre from template
  template:
    src: etc/spamassassin/init.pre
    dest: /etc/spamassassin/init.pre
    owner: root
    group: root
    mode: 0644
  notify:
    - restart spamassassin

- name: update local.cf from template
  template:
    src: etc/spamassassin/local.cf
    dest: /etc/spamassassin/local.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart spamassassin

#- name: update /etc/default/spamass-milter from template
#  template:
#    src: etc/default/spamass-milter
#    dest: /etc/default/spamass-milter
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#    - restart spamassassin

#- name: ensure /var/spool/postfix/spamass directory exists
#  file:
#    path: /var/spool/postfix/spamass
#    owner: spamass-milter
#    group: spam
#    mode: 0750
#    state: directory

- name: ensure spamassassin services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - spamassassin
    - spamass-milter

