---
- name: ensure dependencies available through apt are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - crm114
    - fuzzyocr
    - libmail-dkim-perl
    - pyzor
    - razor
    - sa-compile
    - spamass-milter
    - spamassassin
    - spamassassin-heatu
    - spamassassin-rules-ja

- name: run pyzor discover...
  command: pyzor discover
  changed_when: false

#- name: run razor-admin register...
#  command: razor-admin -home=/etc/spamassassin/.razor -register
#  changed_when: false

#- name: run razor-admin create...
#  command: razor-admin -home=/etc/spamassassin/.razor -create
#  changed_when: false

#- name: run razor-admin discover...
#  command: razor-admin -home=/etc/spamassassin/.razor -discover
#  changed_when: false

- name: update /etc/default/spamassassin from template
  template:
    src: etc/default/spamassassin
    dest: /etc/default/spamassassin
    owner: root
    group: root
    mode: 0644
  notify:
    - restart spamassassin

- name: update init.pre from template
  template:
    src: etc/spamassassin/init.pre
    dest: /etc/spamassassin/init.pre
    owner: root
    group: root
    mode: 0644
  notify:
    - restart spamassassin

- name: update local.cf from template
  template:
    src: etc/spamassassin/local.cf
    dest: /etc/spamassassin/local.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart spamassassin

- name: update /etc/default/spamass-milter from template
  template:
    src: etc/default/spamass-milter
    dest: /etc/default/spamass-milter
    owner: root
    group: root
    mode: 0644
  notify:
    - restart spamassassin

- name: ensure spamassassin services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - spamassassin
    - spamass-milter
