---
- name: restart dovecot
  service:
    name: dovecot
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart opendkim
  service:
    name: opendkim
    state: restarted

- name: restart gld
  service:
    name: gld
    pattern: /usr/sbin/gld
    state: restarted

- name: restart spamassassin
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - spamassassin
    - spamass-milter

