---
- name: restart dovecot
  service:
    name: dovecot
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart sqlgrey
  service:
    name: sqlgrey
    pattern: /usr/sbin/sqlgrey
    state: restarted

- name: restart opendkim
  service:
    name: opendkim
    state: restarted

# ansible service module doesn't seem to work correctly with clamav
- name: restart clamav
  command: service {{ item }} restart
  with_items:
    - clamav-daemon
    - clamav-milter

- name: restart dspam
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - dspam
    - dspam-milter

- name: restart spamassassin
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - spamassassin
    - spamass-milter

