---
- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart opendkim
  service:
    name: postfix
    state: opendkim

- name: restart amavis
  service:
    name: amavis
    state: restarted
