---
- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart opendkim
  service:
    name: opendkim
    state: restarted

- name: restart gld
  service:
    name: gld
    state: restarted
    pattern: /usr/sbin/gld

- name: restart amavis
  service:
    name: amavis
    state: restarted
